const SET_BENEFICIARIES = "SET_BENEFICIARIES";
const ADD_BENEFICIARY = "ADD_BENEFICIARY";
const DELETE_BENEFICIARY = "DELETE_BENEFICIARY";
const EDIT_BENEFICIARY = "EDIT_BENEFICIARY";

export default {
  SET_BENEFICIARIES,
  ADD_BENEFICIARY,
  DELETE_BENEFICIARY,
  EDIT_BENEFICIARY,
};
